--CREATE DATABASE vvtDA1
GO

USE vvtDA1
GO



----------------------------Tạo bảng------------------------------------
CREATE TABLE TaiKhoan
(TenTK CHAR(20) PRIMARY KEY,
MK CHAR(20), 
TenHT NVARCHAR(20) NOT NULL
)	
INSERT INTO TaiKhoan(TenTK, MK, TenHT)
VALUES
('ad','adadad',N'Quản lý'),
('nv','nvnvnv',N'Nhân viên')

--KHÁCH HÀNG
CREATE TABLE KhachHang
(MaKH CHAR(10) PRIMARY KEY,
HoTen NVARCHAR(30) NOT NULL,
GioiTinh NVARCHAR(3) CHECK (GioiTinh IN ('Nam',N'Nữ')),
DiaChi NVARCHAR(100),
Sdt CHAR(10) UNIQUE CHECK (Sdt LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
HangKH NVARCHAR(20)
)

--NHÂN VIÊN
CREATE TABLE NhanVien
(MaNV CHAR(10) PRIMARY KEY,
TenNV NVARCHAR(30) NOT NULL,
GioiTinh NVARCHAR(5) CHECK(GioiTinh IN('Nam', N'Nữ')),
DiaChi NVARCHAR(50),
Sdt CHAR(10) UNIQUE CHECK (Sdt LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
VaiTro NVARCHAR(30) NOT NULL,
LuongCB INT DEFAULT 0
)

 --THƯƠNG HIỆU
CREATE TABLE ThuongHieu
(MaTH CHAR(10) PRIMARY KEY,
TenTH NVARCHAR(30) NOT NULL,
DiaChiTH NVARCHAR(100),
SdtTH CHAR(20) UNIQUE
)


--SẢN PHẨM
CREATE TABLE SanPham
(MaSP CHAR(10) PRIMARY KEY,
TenSP NVARCHAR(50) NOT NULL,
MaTH CHAR(10) REFERENCES ThuongHieu(MaTH) ON UPDATE CASCADE ON DELETE CASCADE,
DonGia INT DEFAULT 0
)

CREATE TABLE Size 
(SizeVN INT PRIMARY KEY,
SizeUS INT,
SizeUK INT,
Centimeter FLOAT
)
CREATE TABLE MauSac 
(MaMau CHAR(10) PRIMARY KEY,
TenMau NVARCHAR(50)
)

CREATE TABLE SanPham_CT 
(MaSP CHAR(10),
SizeVN INT,
MaMau CHAR(10),
TenMau NVARCHAR(50),
PRIMARY KEY (MaSP, SizeVN, MaMau),
FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (SizeVN) REFERENCES Size(SizeVN) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (MaMau) REFERENCES MauSac(MaMau) ON UPDATE CASCADE ON DELETE CASCADE
)

--KHO
CREATE TABLE Kho
(MaSP CHAR(10),
SizeVN INT,
MaMau CHAR(10),
SLTon INT DEFAULT 0,
PRIMARY KEY (MaSP, SizeVN, MaMau),
CONSTRAINT FK_Kho_CTSP FOREIGN KEY (MaSP, SizeVN, MaMau) REFERENCES SanPham_CT(MaSP, SizeVN, MaMau) ON UPDATE CASCADE ON DELETE CASCADE
)

--KHUYẾN MÃI
CREATE TABLE KhuyenMai
(MaKM CHAR(10) PRIMARY KEY,
MaSP CHAR(10) REFERENCES SanPham(MaSP) ON UPDATE CASCADE ON DELETE CASCADE,
NgayBD DATE,
NgayKT DATE,
GiamGia INT DEFAULT 0,
HangKH NVARCHAR(20)
)


--HÓA ĐƠN NHẬP
CREATE TABLE HDN
(MaHDN CHAR(10) PRIMARY KEY,
NgayNhap DATE NOT NULL,
DonGia INT DEFAULT 0
)

--HÓA ĐƠN BÁN
CREATE TABLE HDB
(MaHDB CHAR(10) PRIMARY KEY,
NgayBan DATE NOT NULL,
DonGia INT DEFAULT 0
)

--CHI TIẾT BÁN
CREATE TABLE ChiTietHDB
(MaCTB CHAR(20) PRIMARY KEY,
MaHDB CHAR(10) REFERENCES HDB(MaHDB) ON UPDATE CASCADE ON DELETE CASCADE,
MaKH CHAR(10) REFERENCES KhachHang(MaKH) ON UPDATE CASCADE,

MaSP CHAR(10),
SizeVN INT,
MaMau CHAR(10),

SL INT DEFAULT 0,
MaNV CHAR(10) REFERENCES NhanVien(MaNV) ON UPDATE CASCADE,
CONSTRAINT FK_CTBan_CTSP FOREIGN KEY (MaSP, SizeVN, MaMau) REFERENCES SanPham_CT(MaSP, SizeVN, MaMau) ON UPDATE CASCADE ON DELETE CASCADE
)

--CHI TIẾT NHẬP
CREATE TABLE ChiTietHDN
(MaCTN CHAR(20) PRIMARY KEY,
MaHDN CHAR(10) REFERENCES HDN(MaHDN) ON UPDATE CASCADE ON DELETE CASCADE,
MaTH CHAR(10) REFERENCES ThuongHieu(MaTH),

MaSP CHAR(10),
SizeVN INT,
MaMau CHAR(10),

SL INT DEFAULT 0,
MaNV CHAR(10) REFERENCES NhanVien(MaNV) ON UPDATE CASCADE,
CONSTRAINT FK_CTNhap_CTSP FOREIGN KEY (MaSP, SizeVN, MaMau) REFERENCES SanPham_CT(MaSP, SizeVN, MaMau) ON UPDATE CASCADE ON DELETE CASCADE
)




 --
SELECT MaKH, HoTen, HangKH
FROM KhachHang

--
SELECT SanPham_CT.MaSP, TenSP, SizeVN, MaMau, TenMau
FROM SanPham_CT INNER JOIN SanPham
on SanPham_CT.MaSP = SanPham.MaSP

--Kho
SELECT Kho.MaSP, TenSP, SizeVN, TenMau, ThuongHieu.TenTH, SLTon 
FROM Kho INNER JOIN SanPham 
ON Kho.MaSP = SanPham.MaSP INNER JOIN ThuongHieu 
ON SanPham.MaTH = ThuongHieu.MaTH INNER JOIN MauSac 
ON MauSac.MaMau = Kho.MaMau

--sản phẩm + slton
SELECT SanPham.MaSP, TenSP, TenTH, Kho.SizeVN, Kho.MaMau, DonGia, SLTon
FROM SanPham INNER JOIN Kho
ON SanPham.MaSP = Kho.MaSP INNER JOIN ThuongHieu
ON ThuongHieu. MaTH = SanPham.MaTH

--slton kho thấp
SELECT Kho.MaSP, TenSP, SizeVN, TenMau, ThuongHieu.TenTH, SLTon 
FROM Kho INNER JOIN SanPham 
ON Kho.MaSP = SanPham.MaSP INNER JOIN ThuongHieu 
ON SanPham.MaTH = ThuongHieu.MaTH INNER JOIN MauSac 
ON MauSac.MaMau = Kho.MaMau
WHERE SLTon <= 10

--Tính SLTon theo MaSP 
SELECT SanPham.MaSP, TenSP, TenTH, DonGia, SL = SUM(ISNULL(Kho.SLTon, 0)) 
FROM SanPham LEFT JOIN Kho 
ON SanPham.MaSP = Kho.MaSP INNER JOIN ThuongHieu 
ON ThuongHieu.MaTH = SanPham.MaTH
GROUP BY SanPham.MaSP, TenSP, TenTH, DonGia

--CT + Kho
SELECT SanPham_CT.MaSP, TenSP, SanPham_CT.SizeVN, TenMau, SLTon
FROM SanPham_CT INNER JOIN Kho
ON SanPham_CT.MaSP = Kho.MaSP 
AND SanPham_CT.SizeVN = Kho.SizeVN 
AND SanPham_CT.MaMau = Kho.MaMau INNER JOIN SanPham
ON SanPham_CT.MaSP = SanPham.MaSP

--KH + HDB
SELECT KhachHang.MaKH, HoTen, HDB.MaHDB, NgayBan
FROM KhachHang INNER JOIN ChiTietHDB
ON KhachHang.MaKH = ChiTietHDB.MaKH INNER JOIN HDB
ON HDB.MaHDB = ChiTietHDB.MaHDB

--tính sum số HDB cho từng maKH-> HangKH
SELECT KhachHang.MaKH, HoTen, TongHD = SUM(DonGia), SoHD = COUNT(DISTINCT HDB.MaHDB)
FROM KhachHang INNER JOIN ChiTietHDB
ON KhachHang.MaKH = ChiTietHDB.MaKH INNER JOIN HDB
ON HDB.MaHDB = ChiTietHDB.MaHDB
GROUP BY KhachHang.MaKH, HoTen

--KH + HDB
SELECT KhachHang.MaKH, HoTen, HDB.MaHDB, NgayBan, HDB.DonGia, TenSP, SizeVN, TenMau
FROM KhachHang INNER JOIN ChiTietHDB
ON KhachHang.MaKH = ChiTietHDB.MaKH INNER JOIN HDB
ON HDB.MaHDB = ChiTietHDB.MaHDB INNER JOIN MauSac
ON ChiTietHDB.MaMau = MauSac.MaMau INNER JOIN SanPham
ON SanPham.MaSP = ChiTietHDB.MaSP
WHERE KhachHang.MaKH = @MaKH

--CTB +++
SELECT MaCTB, ChiTietHDB.MaHDB, HoTen, TenSP, SizeVN, TenMau, SL, MaNV
FROM ChiTietHDB INNER JOIN HDB
ON ChiTietHDB.MaHDB = HDB.MaHDB INNER JOIN KhachHang
ON ChiTietHDB.MaKH = KhachHang.MaKH INNER JOIN SanPham
ON SanPham.MaSP = ChiTietHDB.MaSP INNER JOIN MauSac
ON MauSaC.MaMau = ChiTietHDB.MaMau