--CREATE DATABASE vvtDA1
GO

USE vvtDA1
GO



----------------------------Tạo bảng------------------------------------
CREATE TABLE TaiKhoan
(TenTK CHAR(20) PRIMARY KEY,
Mk CHAR(20), 
Access NVARCHAR(20) NOT NULL
)

--KHÁCH HÀNG
CREATE TABLE KhachHang
(MaKH CHAR(10) PRIMARY KEY,
HoTen NVARCHAR(30) NOT NULL,
GioiTinh NVARCHAR(3) CHECK (GioiTinh IN ('Nam',N'Nữ')),
DiaChi NVARCHAR(100),
Sdt CHAR(10) UNIQUE CHECK (Sdt LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
HangKH NVARCHAR(20)
)

--NHÂN VIÊN
CREATE TABLE NhanVien
(MaNV CHAR(10) PRIMARY KEY,
TenNV NVARCHAR(30) NOT NULL,
GioiTinh NVARCHAR(5) CHECK(GioiTinh IN('Nam', N'Nữ')),
DiaChi NVARCHAR(50),
Sdt CHAR(10) UNIQUE CHECK (Sdt LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
VaiTro NVARCHAR(30) NOT NULL,
LuongCB INT DEFAULT 0
)

 --THƯƠNG HIỆU
CREATE TABLE ThuongHieu
(MaTH CHAR(10) PRIMARY KEY,
TenTH NVARCHAR(30) NOT NULL,
DiaChiTH NVARCHAR(100),
SdtTH CHAR(20) UNIQUE
)


--SẢN PHẨM
CREATE TABLE SanPham
(MaSP CHAR(10) PRIMARY KEY,
TenSP NVARCHAR(50) NOT NULL,
MaTH CHAR(10) REFERENCES ThuongHieu(MaTH) ON UPDATE CASCADE ON DELETE CASCADE,
DonGia INT DEFAULT 0
)

CREATE TABLE Size 
(SizeVN INT PRIMARY KEY,
SizeUS INT,
SizeUK INT,
Centimeter FLOAT
)
CREATE TABLE MauSac 
(MaMau CHAR(10) PRIMARY KEY,
TenMau NVARCHAR(50)
)

CREATE TABLE SanPham_Size 
(MaSP CHAR(10),
SizeVN INT,
PRIMARY KEY (MaSP, SizeVN),
FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP),
FOREIGN KEY (SizeVN) REFERENCES Size(SizeVN)
)
--insert into SanPham_Size(MaSP, SizeVN)
--values('SP001', 35)

CREATE TABLE SanPham_MauSac 
(MaSP CHAR(10),
MaMau CHAR(10),
TenMau NVARCHAR(50),
PRIMARY KEY (MaSP, MaMau),
FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP),
FOREIGN KEY (MaMau) REFERENCES MauSac(MaMau)
)

--KHO
CREATE TABLE Kho
(MaSP CHAR(10),
SizeVN INT,
MaMau CHAR(10),
SLTon INT DEFAULT 0,
PRIMARY KEY (MaSP, SizeVN, MaMau),
CONSTRAINT FK_Kho_SP FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_Kho_Size FOREIGN KEY (SizeVN) REFERENCES Size(SizeVN) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_Kho_MS FOREIGN KEY (MaMau) REFERENCES MauSac(MaMau) ON UPDATE CASCADE ON DELETE CASCADE
)

--HÓA ĐƠN NHẬP
CREATE TABLE HDN
(MaHDN CHAR(10) PRIMARY KEY,
NgayNhap DATE NOT NULL,
DonGia INT DEFAULT 0
)

--HÓA ĐƠN BÁN
CREATE TABLE HDB
(MaHDB CHAR(10) PRIMARY KEY,
NgayBan DATE NOT NULL,
DonGia INT DEFAULT 0
)

CREATE TABLE ChiTietHDB
(MaHDB CHAR(10),
MaSP CHAR(10),
MaKH CHAR(10),
SL INT DEFAULT 0,
MaNV CHAR(10),
CONSTRAINT PK_CTHDB PRIMARY KEY (MaHDB, MaSP),
CONSTRAINT FK_HDB_CT FOREIGN KEY (MaHDB) REFERENCES HDB(MaHDB) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_NV_HDB FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
CONSTRAINT FK_SP_HDB FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP),
CONSTRAINT FK_KH_HDB FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
)

CREATE TABLE ChiTietHDN
(MaHDN CHAR(10),
MaSP CHAR(10),
MaTH CHAR(10),
SL INT DEFAULT 0,
MaNV CHAR(10),
CONSTRAINT PK_CTHDN PRIMARY KEY (MaHDN, MaSP),
CONSTRAINT FK_HDN_CT FOREIGN KEY (MaHDN) REFERENCES HDN(MaHDN) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_NV_HDN FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
CONSTRAINT FK_SP_HDN FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP),
CONSTRAINT FK_TH_HDN FOREIGN KEY (MaTH) REFERENCES ThuongHieu(MaTH)
)

CREATE TABLE KhuyenMai
(MaKM CHAR(10) PRIMARY KEY,
MaSP CHAR(10) REFERENCES SanPham(MaSP) ON UPDATE CASCADE ON DELETE CASCADE,
NgayBD DATE,
NgayKT DATE,
GiamGia INT DEFAULT 0
)

--Size + SP
SELECT SanPham_Size.MaSP, TenSP, SanPham_Size.SizeVN
FROM SanPham_Size INNER JOIN SanPham
ON SanPham_Size.MaSP = SanPham.MaSP

--MauSac + SP + TenMau
SELECT SanPham.MaSP, TenSP, MauSac.MaMau, TenMau
FROM SanPham_MauSac INNER JOIN SanPham
ON SanPham_MauSac.MaSP = SanPham.MaSP INNER JOIN MauSac
ON SanPham_MauSac.MaMau = MauSac.MaMau

--Kho
SELECT Kho.MaSP, TenSP, ThuongHieu.TenTH, MaSize, MaMau, SLTon
FROM Kho INNER JOIN SanPham
ON Kho.MaSP = SanPham.MaSP INNER JOIN ThuongHieu
ON SanPham.MaSP = ThuongHieu.MaTH

--sản phẩm + slton
SELECT SanPham.MaSP, TenSP, TenTH, Kho.MaSize, Kho.MaMau, DonGia, SLTon
FROM SanPham INNER JOIN Kho
ON SanPham.MaSP = Kho.MaSP INNER JOIN ThuongHieu
ON ThuongHieu. MaTH = SanPham.MaTH

--tính sum HDB cho từng maKH-> HangKH