--CREATE DATABASE vvtDA1
GO

USE vvtDA1
GO


----------------------------Tạo bảng------------------------------------
CREATE TABLE TaiKhoan
(TenTK CHAR(20) PRIMARY KEY,
Mk CHAR(20), 
Access NVARCHAR(20) NOT NULL
)

--KHÁCH HÀNG
CREATE TABLE KhachHang
(MaKH CHAR(10) PRIMARY KEY,
HoTen NVARCHAR(30) NOT NULL,
GioiTinh NVARCHAR(3) CHECK (GioiTinh IN ('Nam','Nữ')),
DiaChi NVARCHAR(100),
Sdt CHAR(10) UNIQUE CHECK (Sdt LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
HangKH NVARCHAR(20)
)

--NHÂN VIÊN
CREATE TABLE NhanVien
(MaNV CHAR(10) PRIMARY KEY,
TenNV NVARCHAR(30) NOT NULL,
GioiTinh NVARCHAR(5) CHECK(GioiTinh IN('Nam', 'Nữ')),
DiaChi NVARCHAR(50),
Sdt CHAR(10) UNIQUE CHECK (Sdt LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
VaiTro NVARCHAR(30) NOT NULL,
LuongCB INT DEFAULT 0
)

 --THƯƠNG HIỆU
CREATE TABLE ThuongHieu
(MaTH CHAR(10) PRIMARY KEY,
TenTH NVARCHAR(30) NOT NULL,
DiaChiTH NVARCHAR(100),
SdtTH CHAR(20) UNIQUE
)


--SẢN PHẨM
CREATE TABLE SanPham
(MaSP CHAR(10) PRIMARY KEY,
TenSP NVARCHAR(50) NOT NULL,
MaTH CHAR(10) REFERENCES ThuongHieu(MaTH) ON UPDATE CASCADE ON DELETE CASCADE,
DonGia INT DEFAULT 0
)

--KHO
CREATE TABLE Kho
(MaSP CHAR(10) PRIMARY KEY,
SLTon INT DEFAULT 0,
CONSTRAINT FK_Kho_SanPham FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON UPDATE CASCADE ON DELETE CASCADE
)

--HÓA ĐƠN NHẬP
CREATE TABLE HDN
(MaHDN CHAR(10) PRIMARY KEY,
NgayNhap DATE NOT NULL,
DonGia INT DEFAULT 0
)

--HÓA ĐƠN BÁN
CREATE TABLE HDB
(MaHDB CHAR(10) PRIMARY KEY,
NgayBan DATE NOT NULL,
DonGia INT DEFAULT 0
)

CREATE TABLE ChiTietHDB
(MaHDB CHAR(10),
MaSP CHAR(10),
MaKH CHAR(10),
SL INT DEFAULT 0,
MaNV CHAR(10),
CONSTRAINT PK_CTHDB PRIMARY KEY (MaHDB, MaSP),
CONSTRAINT FK_HDB_CT FOREIGN KEY (MaHDB) REFERENCES HDB(MaHDB) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_NV_HDB FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
CONSTRAINT FK_SP_HDB FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP),
CONSTRAINT FK_KH_HDB FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
)

CREATE TABLE ChiTietHDN
(MaHDN CHAR(10),
MaSP CHAR(10),
MaTH CHAR(10),
SL INT DEFAULT 0,
MaNV CHAR(10),
CONSTRAINT PK_CTHDN PRIMARY KEY (MaHDN, MaSP),
CONSTRAINT FK_HDN_CT FOREIGN KEY (MaHDN) REFERENCES HDN(MaHDN) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_NV_HDN FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
CONSTRAINT FK_SP_HDN FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP),
CONSTRAINT FK_TH_HDN FOREIGN KEY (MaTH) REFERENCES ThuongHieu(MaTH)
)

CREATE TABLE KhuyenMai
(MaKM CHAR(10) PRIMARY KEY,
MaSP CHAR(10) REFERENCES SanPham(MaSP) ON UPDATE CASCADE ON DELETE CASCADE,
NgayBD DATE,
NgayKT DATE,
GiamGia INT DEFAULT 0
)

--Kho
SELECT Kho.MaSP, TenSP, ThuongHieu.TenTH, Kho.SLTon
FROM Kho INNER JOIN SanPham
ON Kho.MaSP = SanPham.MaSP INNER JOIN ThuongHieu
ON SanPham.MaSP = ThuongHieu.MaTH

--sản phẩm + slton
SELECT SanPham.MaSP, TenSP, TenTH, DonGia, SLTon
FROM SanPham INNER JOIN Kho
ON SanPham.MaSP = Kho.MaSP INNER JOIN ThuongHieu
ON ThuongHieu. MaTH = SanPham.MaTH

--tính sum HDB cho từng maKH-> HangKH